version: '3.7'
services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    volumes:
      - ./data/adguard/work:/opt/adguardhome/work
      - ./data/adguard/conf:/opt/adguardhome/conf
    restart: always
    networks:
      default:
        ipv4_address: 10.2.0.100

networks:
  default:
    external:
      name: wireguard
