version: '3.7'
services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    volumes:
      - ./private/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy-config:/config
      - ./data/caddy-data:/data
    env_file:
      - private/caddy.env
    networks:
      wireguard:
        ipv4_address: 10.2.0.10

networks:
  wireguard:
    external:
      name: wireguard
