version: '3.7'
services:
  changedetection:
    image: dgtlmoon/changedetection.io
    container_name: changedetection
    restart: always
    volumes:
      - ./data/changedetection:/datastore

networks:
  default:
    external:
      name: caddy
