version: '3.7'
services:
  linkding:
    image: sissbruecker/linkding:latest
    container_name: linkding
    restart: unless-stopped
    volumes:
      - ./data/linkding:/etc/linkding/data

networks:
  default:
    external:
      name: wireguard
