version: '3.7'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./data/nginx:/etc/nginx
    networks:
      wireguard:
        ipv4_address: 10.2.0.111

networks:
  wireguard:
    external:
      name: wireguard
