version: '3.7'
services:
  organizr:
    image: organizr/organizr
    container_name: organizr
    restart: unless-stopped
    volumes:
      - ./data/organizr:/config

networks:
  default:
    external:
      name: wireguard
