version: "3.7"
services:
  redbot:
    container_name: Red-DiscordBot
    image: phasecorex/red-discordbot
    restart: unless-stopped
    volumes:
      - ./data/Red-DiscordBot-data:/data
    environment:
      - PREFIX=.
      - TZ=America/Toronto
