version: '3.7'
services:
  standardnotes-extensions:
    image: mtoohey/standardnotes-extensions
    container_name: standardnotes-extensions
    restart: "no"
    volumes:
      - ./private/sn-extensions.env:/build/.env
      - ./data/sn-extensions/extensions:/build/extensions
      - ./data/caddy-data/public/sn-extensions:/build/public
