version: '3.7'
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: my-syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/syncthing:/var/syncthing
    restart: unless-stopped

networks:
  default:
    external:
      name: wireguard
