version: '3.7'
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    restart: always
    volumes:
      - ./data/uptime-kuma:/app/data

networks:
  default:
    external:
      name: wireguard
