version: '3.7'
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - PEERDNS=10.2.0.100 # Adguard
      - ALLOWEDIPS=10.2.0.0/24 # Allow local IPs (10.20.0.*)
    env_file: private/wg.env
    volumes:
      - ./data/wireguard:/config
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
    network_mode: "container:gluetun"
