# Inspired from https://github.com/IAmStoxe/wirehole
version: '3.7'

networks:
  private_network:
    name: wireguard
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - PEERDNS=10.2.0.100 # Adguard
      - ALLOWEDIPS=10.2.0.0/24 # Allow local IPs (10.20.0.*)
    env_file: private/wg.env
    volumes:
      - ./data/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 10.2.0.3

  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    volumes:
      - ./data/unbound:/opt/unbound/etc/unbound
    restart: unless-stopped
    network_mode: "service:gluetun"

  adguard:
    image: adguard/adguardhome
    container_name: adguard
    volumes:
      - ./data/adguard/work:/opt/adguardhome/work
      - ./data/adguard/conf:/opt/adguardhome/conf
    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 10.2.0.100

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    env_file: private/gluetun.env
    network_mode: "service:wireguard"
